- hosts: all
  roles:
    - role: init
      key_path: ../../../integration-tests/config/leappto_testing_key.pub
    - httpd
    - role: mysql
      package_name: mariadb
      service_name: mariadb
    - role: php
      repo_version: 7
    - phpmyadmin
